---
ansible_ssh_common_args: '-o "UserKnownHostsFile=/dev/null" -o "StrictHostKeyChecking=no" -o ProxyCommand="ssh -W %h:%p ubuntu@{{ jump_host }}"'
ansible_ssh_private_key_file: ~/.ssh/id_rsa
nginx_conf_file: /etc/nginx/sites-available/default
ansible_user: ubuntu
jump_host: '{{ groups.vm_jump[0] }}'