---
- name: download backend release
  get_url:
    url:  https://github.com/piragunka/snatch/releases/download/backend/code.tar.gz
    dest: /home/ubuntu

- name: extract archive
  shell: "tar -zxvf 'code.tar.gz'"

- name: chmod
  shell: chmod 775 /home/ubuntu/code/manage.py
    
- name: install pip
  apt: name=python3-pip state=latest
  
- name: install requirements
  pip:
    requirements: /home/ubuntu/code/requirements.txt
  
- name: install gunicorn
  apt: name=gunicorn state=latest

- name: copy setting django
  template: src=templates/.env dest=/home/ubuntu/code/.env mode=0775

- name: copy gunicorn.socket
  template: src=templates/gunicorn.socket dest=/etc/systemd/system/gunicorn.socket mode=0775

- name: copy gunicorn.service
  template: src=templates/gunicorn.service dest=/etc/systemd/system/gunicorn.service mode=0775
      
- name: run gunicorn
  command: sudo systemctl enable --now gunicorn.socket
