---
- name: copy django project
  copy: src=files/code dest=/home/ubuntu/ mode=0775  force=no

- name: Install pip
  apt: name=python3-pip state=latest
  
- name: install requirements
  pip:
    requirements: /home/ubuntu/code/requirements.txt
  
- name: Install gunicorn
  apt: name=gunicorn state=latest

- name: copy setting django
  template: src=templates/.env dest=/home/ubuntu/.env mode=0775

- name: copy gunicorn.socket
  template: src=templates/gunicorn.socket dest=/etc/systemd/system/gunicorn.socket mode=0775

- name: copy gunicorn.service
  template: src=templates/gunicorn.service dest=/etc/systemd/system/gunicorn.service mode=0775
      
- name: run gunicorn
  command: sudo systemctl enable --now gunicorn.socket