---
- name: backend1
  hosts: vm_backend1, vm_backend2, vm_frontend
  become: True

  roles:
    - { role: nginx, tags: [nginx] }
          
- name: db
  hosts: vm_db
  become: True
  
  roles:
    - { role: postgres, tags: [postgres] }

